#!/bin/sh

dir=$(pwd)

cd $dir;
cd ../;

echo "Run AbstractCachedTransfer Test \n"
php public/index-test-generate-cache.php;
php public/index-test-cache.php;
if [ $? -ne 0 ]; then
  exit 1
fi

echo "Run AbstractCastTransfer Test \n"
php public/index-test-cast.php;
if [ $? -ne 0 ]; then
  exit 1
fi

echo "Run AbstractCastDynamicTransfer Test \n"
php public/index-test-cast-dynamic.php;
if [ $? -ne 0 ]; then
  exit 1
fi

echo "Run AbstractConfigurableTransfer Test \n"
php public/index-test-configurable.php;
if [ $? -ne 0 ]; then
  exit 1
fi

echo "Run AbstractConfigurableTransfer for traits Test \n"
php public/index-test-generate-traits.php;
php public/index-test-traits.php;

echo "Finished!\n"