#!/bin/sh

dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

cd $dir;
cd ../;

echo "Creating Transfers for tests...";
php public/index-test-create-transfers.php;
if [ $? -ne 0 ]; then
  exit 1
fi

sleep 1

echo "Run index-test-generate-cache Test \n"
php public/index-test-generate-cache.php;
if [ $? -ne 0 ]; then
  exit 1
fi

sleep 1

echo "Run index-test-generate-traits Test \n"
php public/index-test-generate-traits.php;
if [ $? -ne 0 ]; then
  exit 1
fi

sleep 1

echo "Run index-test-generate-php-doc Test \n"
php public/index-test-generate-php-doc.php;
if [ $? -ne 0 ]; then
  exit 1
fi

sleep 1

echo "running test for transfers: \n"
php public/index-test-transfers.php;

echo "Finished!\n"